/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica1ipc2.frontend;

/**
 *
 * @author arcan
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdmin = new javax.swing.JMenu();
        btnGestionPersonal = new javax.swing.JMenuItem();
        btnGestionNominas = new javax.swing.JMenuItem();
        MenuAlmacen = new javax.swing.JMenu();
        btnGestionInventario = new javax.swing.JMenuItem();
        btnGestionMenu = new javax.swing.JMenuItem();
        MenuOperaciones = new javax.swing.JMenu();
        btnControlMesas = new javax.swing.JMenuItem();
        btnGestionCuentas = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        btnFlujoCaja = new javax.swing.JMenuItem();
        btnProductosMasVendidos = new javax.swing.JMenuItem();
        btnBajoStock = new javax.swing.JMenuItem();
        btnExportarMenu = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        jMenuItem8.setText("jMenuItem8");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        MenuAdmin.setText("Administracion");

        btnGestionPersonal.setText("Gestion de Personal");
        MenuAdmin.add(btnGestionPersonal);

        btnGestionNominas.setText("Gestion de Nominas");
        MenuAdmin.add(btnGestionNominas);

        jMenuBar1.add(MenuAdmin);

        MenuAlmacen.setText("Almacen");

        btnGestionInventario.setText("Gestion de Inventario");
        MenuAlmacen.add(btnGestionInventario);

        btnGestionMenu.setText("Gestion de Menu");
        MenuAlmacen.add(btnGestionMenu);

        jMenuBar1.add(MenuAlmacen);

        MenuOperaciones.setText("Operaciones");

        btnControlMesas.setText("Control de Mesas");
        MenuOperaciones.add(btnControlMesas);

        btnGestionCuentas.setText("Gestion de Cuentas");
        btnGestionCuentas.addActionListener(this::btnGestionCuentasActionPerformed);
        MenuOperaciones.add(btnGestionCuentas);

        jMenuBar1.add(MenuOperaciones);

        MenuReportes.setText("Reportes");

        btnFlujoCaja.setText("Flujo de Caja");
        MenuReportes.add(btnFlujoCaja);

        btnProductosMasVendidos.setText("Productos Mas Vendidos");
        MenuReportes.add(btnProductosMasVendidos);

        btnBajoStock.setText("Insumos con Bajo Stock");
        MenuReportes.add(btnBajoStock);

        jMenuBar1.add(MenuReportes);

        btnExportarMenu.setText("Exportar Menu");
        jMenuBar1.add(btnExportarMenu);

        btnSalir.setText("Salir");
        jMenuBar1.add(btnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuAlmacen;
    private javax.swing.JMenu MenuOperaciones;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenuItem btnBajoStock;
    private javax.swing.JMenuItem btnControlMesas;
    private javax.swing.JMenu btnExportarMenu;
    private javax.swing.JMenuItem btnFlujoCaja;
    private javax.swing.JMenuItem btnGestionCuentas;
    private javax.swing.JMenuItem btnGestionInventario;
    private javax.swing.JMenuItem btnGestionMenu;
    private javax.swing.JMenuItem btnGestionNominas;
    private javax.swing.JMenuItem btnGestionPersonal;
    private javax.swing.JMenuItem btnProductosMasVendidos;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}

